apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: governed-pipeline-deny-all
  namespace: governed-pipeline
spec:
  podSelector:
    matchLabels:
      app: governed-pipeline
  policyTypes:
    - Ingress
    - Egress

